### ISSUE TITLE
help me thanks

### ISSUE THREAD

**Issue by yzk-lab** [ming71/Cascade-Rotated-RetinaNet#3]
当我使用 pip install git+git://github.com/lehduong/torch-warmup-lr.git这句指令时出这个错 搞了好久解决不了 有什么办法吗？谢谢你
![image](https://user-images.githubusercontent.com/41197028/109932447-2a204b00-7d05-11eb-9bb0-b7cacbf5ac8d.png)

**Comment by ZealianMa** [comment]
Hi，请问你是用conda环境吗？我也碰到这个问题。
